import type { AIProvider, GenerateResumeDraftInput } from "@/lib/ai/types";
import type { ResumeDraftOutput } from "@/lib/types";
import { analyzeJobDescription } from "@/lib/services/jd-analyzer";
import { generateTailoredResume } from "@/lib/services/generate-tailored-resume";
import { parseResume } from "@/lib/services/resume-parser";
import { rewriteBullet } from "@/lib/services/rewrite-bullet";
import { scoreResume } from "@/lib/services/score-resume";
import { buildResumeTextFromProfile } from "@/lib/workshop";

function titleByKey(key: string, language: "en" | "zh") {
  const mapEn: Record<string, string> = {
    summary: "SUMMARY",
    skills: "SKILLS",
    experience: "EXPERIENCE",
    education: "EDUCATION",
    projects: "PROJECTS",
    certifications: "CERTIFICATIONS",
    awards: "AWARDS",
    links: "LINKS",
  };
  const mapZh: Record<string, string> = {
    summary: "个人摘要",
    skills: "技能",
    experience: "工作经历",
    education: "教育背景",
    projects: "项目经历",
    certifications: "证书",
    awards: "奖项",
    links: "链接",
  };

  return language === "zh" ? mapZh[key] ?? key : mapEn[key] ?? key.toUpperCase();
}

export class MockAIProvider implements AIProvider {
  readonly name = "mock" as const;

  async analyzeJobDescription(input: { jobDescriptionText: string }) {
    return analyzeJobDescription(input.jobDescriptionText);
  }

  async scoreResume(input: {
    resumeText: string;
    jobDescriptionText: string;
  }) {
    return scoreResume(input.resumeText, input.jobDescriptionText);
  }

  async rewriteBullet(input: {
    bullet: string;
    mode: Parameters<typeof rewriteBullet>[1];
    jobDescriptionText?: string;
  }) {
    return rewriteBullet(input.bullet, input.mode, input.jobDescriptionText);
  }

  async generateTailoredResume(input: {
    resumeText: string;
    jobDescriptionText: string;
    jobRole: string;
    company: string;
  }) {
    return generateTailoredResume(
      input.resumeText,
      input.jobDescriptionText,
      input.jobRole,
      input.company,
    );
  }

  async generateResumeDraft(input: GenerateResumeDraftInput): Promise<ResumeDraftOutput> {
    const content = buildResumeTextFromProfile({
      title:
        input.profileData.basicProfile.fullName ||
        (input.outputLanguage === "zh" ? "简历草稿" : "Resume Draft"),
      profile: input.profileData,
      fallbackText: "",
    });
    const parsed = parseResume(content);

    return {
      name:
        input.profileData.basicProfile.fullName ||
        (input.outputLanguage === "zh" ? "简历草稿" : "Resume Draft"),
      summary:
        input.profileData.professionalSummary ||
        (input.outputLanguage === "zh"
          ? "已基于当前资料生成草稿，可继续补充量化成果和岗位关键词。"
          : "Draft generated from your current profile. Add quantified impact and role keywords to strengthen it."),
      sections: parsed.sections
        .filter((section) => section.key !== "general")
        .map((section) => ({
          key: section.key,
          title: titleByKey(section.key, input.outputLanguage),
          lines: section.lines,
          bullets: section.bullets,
        })),
      content,
      qualityNotes:
        input.outputLanguage === "zh"
          ? [
              "当前为本地模拟生成（Mock）。",
              "可在第 10 步继续编辑并重新生成。",
            ]
          : [
              "Current output is generated by local mock mode.",
              "Continue editing and regenerate in Step 10.",
            ],
    };
  }
}
